[package]
name = "drone-stm32-map-periph-rtc"
version = "0.11.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
repository = "https://github.com/drone-os/drone-stm32-map"
homepage = "https://www.drone-os.com/"
documentation = "https://api.drone-os.com/drone-stm32-map/0.11/drone_stm32_map_periph_rtc/"
license = "MIT OR Apache-2.0"
description = """
STM32 peripheral mappings for Drone, an Embedded Operating System.
"""

[lib]
path = "lib.rs"

[dependencies.drone-core]
version = "0.11.0"

[dependencies.drone-cortex-m]
version = "0.11.0"

[dependencies.drone-stm32-map-pieces]
version = "=0.11.0"
path = "../../pieces"
